language: node_js
node_js: "8"
branches:
  only:
  - master
cache:
  directories:
    - node_modules
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS petIndustry_DB'
  - npm install
  - npx sequelize-cli db:migrate
  - npx sequelize-cli db:seed:all
